DROP DATABASE IF EXISTS PROJECT_IA;
CREATE DATABASE IF NOT EXISTS PROJECT_IA;
USE PROJECT_IA;

CREATE TABLE IF NOT EXISTS USERS (
    DNI CHAR(8) NOT NULL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PAT_LASTNAME VARCHAR(30) NOT NULL,
    MAT_LASTNAME VARCHAR(30) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ATTENDANCES (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DNI CHAR(8) NOT NULL,
    ATTENDACE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DNI) REFERENCES USERS(DNI)
);

SELECT * FROM ATTENDANCES;
SELECT * FROM USERS;